kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-config
  namespace: grafana
data:
  main_config: |
    app_mode = production

    [server]
    protocol = http
    http_addr = 0.0.0.0

    [users]
    allow_sign_up = false

    [security]
    admin_user = admin
    admin_password = admin
  influx-db-provider: |
    apiVersion: 1

    datasources:
      - name: influx
        type: influxdb
        access: proxy
        url: http://influx-db:8086
        user: jmeter
        database: jmeter
        basicAuth: false
        isDefault: true
        editable: false
        secureJsonData:
          password: jmeter
  
      - name: loki
        type: loki
        access: proxy
        url: http://loki.tracing.svc.cluster.local:3100

      - name: jaeger
        type: jaeger
        access: proxy
        url: http://jaeger.tracing.svc.cluster.local:16686
        jsonData:
          tracesToLogs:
            datasourceUid: 'loki'
            tags: ['namespace']
            mapTagNamesEnabled: false
            filterByTraceID: true
            filterBySpanID: false
